#pragma once

/**
 * Name: Project_Playtime
 * Version: 4_7_23_Hotfix
 */

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
	// --------------------------------------------------
	// # Enums
	// --------------------------------------------------
	/**
	 * BoneSkeletalMesh SK_Huggy.SK_Huggy
	 */
	enum class EBone_SK_Huggy : uint8_t
	{
		Rig                       = 0,
		geo_GRP                   = 1,
		rt_eye_low                = 2,
		lf_eye_low                = 3,
		lips_low                  = 4,
		torso_head_low            = 5,
		hands_low                 = 6,
		lf_leg_low                = 7,
		rt_leg_low                = 8,
		bowtie_low                = 9,
		mouth_inside_low          = 10,
		polySurface69             = 11,
		polySurface68             = 12,
		teeth_gums_low            = 13,
		joints_GRP                = 14,
		body_JNT1                 = 15,
		body_JNT2                 = 16,
		body_JNT3                 = 17,
		body_JNT4                 = 18,
		body_JNT5                 = 19,
		lf_shoulder_JNT           = 20,
		lf_arm_JNT1               = 21,
		lf_arm_JNT2               = 22,
		lf_arm_JNT3               = 23,
		lf_arm_JNT4               = 24,
		lf_arm_JNT5               = 25,
		lf_arm_JNT6               = 26,
		lf_arm_JNT7               = 27,
		lf_arm_JNT8               = 28,
		lf_arm_JNT9               = 29,
		lf_arm_JNT10              = 30,
		lf_arm_JNT11              = 31,
		head_JNT                  = 32,
		mouth_JNT6                = 33,
		mouth_JNT8                = 34,
		head_jaw_JNT              = 35,
		head_rt_JNT               = 36,
		head_lf_JNT               = 37,
		mouth_JNT14               = 38,
		mouth_JNT12               = 39,
		mouth_JNT10               = 40,
		mouth_JNT3                = 41,
		mouth_JNT1                = 42,
		lf_eye_JNT                = 43,
		rt_eye_JNT                = 44,
		mouth_JNT17               = 45,
		rt_shoulder_JNT           = 46,
		rt_arm_JNT1               = 47,
		rt_arm_JNT2               = 48,
		rt_arm_JNT3               = 49,
		rt_arm_JNT4               = 50,
		rt_arm_JNT5               = 51,
		rt_arm_JNT6               = 52,
		rt_arm_JNT7               = 53,
		rt_arm_JNT8               = 54,
		rt_arm_JNT9               = 55,
		rt_arm_JNT10              = 56,
		rt_arm_JNT11              = 57,
		rt_leg_JNT1               = 58,
		rt_leg_JNT2               = 59,
		rt_leg_JNT3               = 60,
		rt_leg_JNT4               = 61,
		rt_leg_JNT5               = 62,
		rt_leg_JNT6               = 63,
		rt_leg_JNT7               = 64,
		rt_leg_JNT8               = 65,
		rt_leg_JNT9               = 66,
		rt_leg_JNT10              = 67,
		rt_leg_JNT11              = 68,
		rt_leg_JNT12              = 69,
		rt_leg_JNT13              = 70,
		lf_leg_JNT1               = 71,
		lf_leg_JNT2               = 72,
		lf_leg_JNT3               = 73,
		lf_leg_JNT4               = 74,
		lf_leg_JNT5               = 75,
		lf_leg_JNT6               = 76,
		lf_leg_JNT7               = 77,
		lf_leg_JNT8               = 78,
		lf_leg_JNT9               = 79,
		lf_leg_JNT10              = 80,
		lf_leg_JNT11              = 81,
		lf_leg_JNT12              = 82,
		lf_leg_JNT13              = 83,
		mouth_close_JNT           = 84,
		Geometry                  = 85,
		huggy_GEO1                = 86,
		rt_foot_ik_JNT            = 87,
		lf_foot_ik_JNT            = 88,
		cog_ik_JNT                = 89,
		huggy_GEO1_end            = 90,
		rt_eye_low_end            = 91,
		lf_eye_low_end            = 92,
		lips_low_end              = 93,
		hands_low_end             = 94,
		bowtie_low_end            = 95,
		mouth_inside_low_end      = 96,
		polySurface69_end         = 97,
		polySurface68_end         = 98,
		teeth_gums_low_end        = 99,
		lf_arm_JNT11_end          = 100,
		mouth_JNT6_end            = 101,
		mouth_JNT8_end            = 102,
		head_rt_JNT_end           = 103,
		head_lf_JNT_end           = 104,
		mouth_JNT14_end           = 105,
		mouth_JNT12_end           = 106,
		mouth_JNT10_end           = 107,
		mouth_JNT3_end            = 108,
		mouth_JNT1_end            = 109,
		lf_eye_JNT_end            = 110,
		rt_eye_JNT_end            = 111,
		mouth_JNT17_end           = 112,
		rt_arm_JNT11_end          = 113,
		rt_leg_JNT13_end          = 114,
		lf_leg_JNT13_end          = 115,
		mouth_close_JNT_end       = 116,
		rt_foot_ik_JNT_end        = 117,
		lf_foot_ik_JNT_end        = 118,
		cog_ik_JNT_end            = 119,
		newfur                    = 120,
		controllers               = 121,
		master_CON_ZERO           = 122,
		rigging                   = 123,
		body_rigging_GRP          = 124,
		body_splineIK_JNT_GRP     = 125,
		body_splineIK_JNT1        = 126,
		body_splineIK_PCI_LOC_GRP = 127,
		body_splineIK_PCI_LOC1    = 128,
		body_splineIK_PCI_LOC2    = 129,
		body_splineIK_GRP2        = 130
	};

	/**
	 * BoneSkeletalMesh SK_PlayerDefault.SK_PlayerDefault
	 */
	enum class EBone_SK_PlayerDefault : uint8_t
	{
		root_JNT                         = 0,
		cog_JNT                          = 1,
		torso_JNT                        = 2,
		head_JNT                         = 3,
		lf_forearm_JNT                   = 4,
		lf_elbow_JNT                     = 5,
		lf_wrist_JNT                     = 6,
		lf_gun_JNT                       = 7,
		rt_forearm_JNT                   = 8,
		rt_elbow_JNT                     = 9,
		rt_wrist_JNT                     = 10,
		rt_gun_JNT                       = 11,
		grabpack_pack_JNT                = 12,
		lf_leg_JNT                       = 13,
		lf_knee_JNT                      = 14,
		lf_foot_JNT                      = 15,
		rt_leg_JNT                       = 16,
		rt_knee_JNT                      = 17,
		rt_foot_JNT                      = 18,
		lf_leg_pole_JNT                  = 19,
		rt_leg_pole_JNT                  = 20,
		lf_arm_pole_JNT                  = 21,
		rt_arm_pole_JNT                  = 22,
		rt_grabpack_tube_deform_JNT1     = 23,
		lf_grabpack_tube_deform_JNT1     = 24,
		rt_grabpack_tube_deform_JNT2     = 25,
		rt_grabpack_tube_deform_JNT3     = 26,
		rt_grabpack_tube_deform_JNT4     = 27,
		rt_grabpack_tube_deform_JNT5     = 28,
		lf_grabpack_tube_deform_JNT5     = 29,
		lf_grabpack_tube_deform_JNT3     = 30,
		lf_grabpack_tube_deform_JNT4     = 31,
		lf_grabpack_tube_deform_JNT2     = 32,
		head_JNT_end                     = 33,
		rt_grabpack_tube_deform_JNT1_end = 34,
		lf_grabpack_tube_deform_JNT1_end = 35,
		rt_grabpack_tube_deform_JNT2_end = 36,
		rt_grabpack_tube_deform_JNT3_end = 37,
		rt_grabpack_tube_deform_JNT4_end = 38,
		rt_grabpack_tube_deform_JNT5_end = 39,
		lf_grabpack_tube_deform_JNT5_end = 40,
		lf_grabpack_tube_deform_JNT3_end = 41,
		lf_grabpack_tube_deform_JNT4_end = 42,
		lf_grabpack_tube_deform_JNT2_end = 43,
		lf_foot_JNT_end                  = 44,
		rt_foot_JNT_end                  = 45,
		lf_leg_pole_JNT_end              = 46,
		rt_leg_pole_JNT_end              = 47,
		lf_arm_pole_JNT_end              = 48,
		rt_arm_pole_JNT_end              = 49,
		rt_foot_ik_JNT                   = 50,
		lf_foot_ik_JNT                   = 51,
		lf_hand_ik_JNT                   = 52,
		rt_hand_ik_JNT                   = 53,
		cog_ik_JNT                       = 54,
		fpcamera_JNT                     = 55
	};

	/**
	 * BoneSkeletalMesh SK_LeftHand.SK_LeftHand
	 */
	enum class EBone_SK_LeftHand : uint8_t
	{
		hand_launcher = 0,
		Misc          = 1,
		L_hand        = 2,
		Hand_L        = 3,
		ThumbB_L      = 4,
		ThumbT_L      = 5,
		ThumbH_L      = 6,
		MiddleB_L     = 7,
		MiddleM_L     = 8,
		MiddleT_L     = 9,
		MiddleH_L     = 10,
		RingB_L       = 11,
		RingM_L       = 12,
		RingT_L       = 13,
		RingH_L       = 14,
		PinkyB_L      = 15,
		PinkyM_L      = 16,
		PinkyT_L      = 17,
		PinkyH_L      = 18,
		IndexB_L      = 19,
		IndexM_L      = 20,
		IndexT_L      = 21,
		IndexH_L      = 22,
		Anim          = 23
	};

	/**
	 * BoneSkeletalMesh SK_VoxelHand.SK_VoxelHand
	 */
	enum class EBone_SK_VoxelHand : uint8_t
	{
		hand_launcher = 0,
		Misc          = 1,
		L_hand        = 2,
		Hand_L        = 3,
		ThumbB_L      = 4,
		ThumbT_L      = 5,
		ThumbH_L      = 6,
		MiddleB_L     = 7,
		MiddleM_L     = 8,
		MiddleT_L     = 9,
		MiddleH_L     = 10,
		RingB_L       = 11,
		RingM_L       = 12,
		RingT_L       = 13,
		RingH_L       = 14,
		PinkyB_L      = 15,
		PinkyM_L      = 16,
		PinkyT_L      = 17,
		PinkyH_L      = 18,
		IndexB_L      = 19,
		IndexM_L      = 20,
		IndexT_L      = 21,
		IndexH_L      = 22,
		Anim          = 23
	};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
